workflow:
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[docker:ci-cd\]/'
      when: always
    - if: '$CI_COMMIT_BRANCH =~ /^(master|main)$/'
      when: always

variables:
  IMAGE_TAG: "unit-tests-base"
  IMAGE_NAME: "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

stages:
  - build
  - test

build:
  stage: build
  image: docker:stable

  services:
    - docker:dind

  script:
    - docker build -t $IMAGE_NAME --file compose/ci-cd.Dockerfile .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_NAME

test:
  stage: test
  image: $IMAGE_NAME

  services:
    - name: mariadb:10.6
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--character-set-client-handshake=FALSE', '--innodb_read_only_compressed=OFF']
    - name: redis
      alias: redis_queue
    - name: redis
      alias: redis_cache
    - name: redis
      alias: redis_socketio

  variables:
    BASE_BRANCH: "develop"
    MYSQL_DATABASE: "test_dodock"
    MYSQL_ROOT_PASSWORD: "test_dodock"

  before_script:
    - export PATH=$PATH:/home/dokotest/.local/bin
    - bench init . --ignore-exist --no-backups --skip-redis-config-generation --skip-assets --frappe-branch $BASE_BRANCH
    - bench config set-common-config -c redis_queue redis://redis_queue:6379 -c redis_cache redis://redis_cache:6379 -c redis_socketio redis://redis_socketio:6379
    - env/bin/python -m pip install --quiet hypothesis==6.68.2 unittest-xml-reporting

    - cp -r apps/frappe/test_sites/test_site sites/
    - sed -i 's/^watch:/# watch:/g' Procfile
    - sed -i 's/^schedule:/# schedule:/g' Procfile
    - sed -i 's/^socketio:/# socketio:/g' Procfile
    - sed -i 's/^redis_socketio:/# redis_socketio:/g' Procfile

    - bench get-app https://gitlab.com/dokos/payments.git --branch develop

    - (bench start > bench_start.log) &
    - bench --site test_site reinstall --yes --mariadb-root-password "$MYSQL_ROOT_PASSWORD" --admin-password "admin"

    - bench --site test_site install-app payments
    - bench build --app payments
