---
- include_tasks: debian_family.yml
  when: ansible_os_family == 'Debian'

- include_tasks: redhat_family.yml
  when: ansible_os_family == "RedHat"

- name: Install yarn
  command: npm install -g yarn
  become: yes
  become_user: root

- name: Set correct permissions on .config folder
  file:
    path: '/home/{{ frappe_user }}/.config'
    owner: '{{ frappe_user }}'
    group: '{{ frappe_user }}'
  become: yes
  become_user: root
...