---
- name: Include distribution-specific variables (if they exist)
  include_vars: "{{ version_specific_vars_file }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
      skip: true
  loop_control:
    loop_var: version_specific_vars_file

- name: install base fonts
  yum:
    name:
      - libXrender
      - libXext
      - xorg-x11-fonts-75dpi
      - xorg-x11-fonts-Type1
    state: present
  when: ansible_os_family == 'RedHat'

- name: install base fonts
  apt:
    pkg:
      - libxrender1
      - libxext6
      - xfonts-75dpi
      - xfonts-base
    state: present
    force: yes
  when: ansible_os_family == 'Debian'

- name: Download wkhtmltopdf
  get_url:
    url: "{{ package_source }}"
    dest: "{{ download_dest }}"
    checksum: "{{ package_checksum }}"

- name: Install wkhtmltopdf (Debian-ish)
  apt:
    deb: "{{ download_dest }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Install wkhtmltopdf (Red-hat-ish)
  yum:
    name: "{{ download_dest }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'
...