# See https://wkhtmltopdf.org/downloads.html for checksums.
package_source: 'https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox-0.12.5-1.centos8.{{ "x86_64" if ansible_architecture == "x86_64" else "i686"}}.rpm'
download_dest: '/tmp/wkhtmltox-0.12.5-1.centos8.{{ "x86_64" if ansible_architecture == "x86_64" else "i686"}}.rpm'